script:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
  - mix test && git push -f gigalixir HEAD:refs/heads/master
language: elixir
elixir: 1.8
otp_release: 21.0
services:
  - postgresql
before_script:
  - PGPASSWORD=postgres psql -c 'create database afy_test;' -U postgres
  - PGPASSWORD=postgres psql -c "CREATE USER andresyepes WITH ENCRYPTED PASSWORD 'password';" -U postgres
  - PGPASSWORD=postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE afy_test TO andresyepes;' -U postgres
