script:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
  - mix test && git push -f gigalixir HEAD:refs/heads/master
  - mix ecto.migrate
language: elixir
elixir: 1.8
otp_release: 21.0
services:
  - postgresql
before_script:
  - PGPASSWORD=postgres psql -c 'create database afy_test;' -U postgres
